# Generated by Django 5.2 on 2025-05-01 23:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_profile_account_status_profile_is_logged_in_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notif_type', models.CharField(choices=[('LOW_STOCK', 'Low Stock'), ('TRIAL_ENDING', 'Trial Ending Soon'), ('SUB_STARTED', 'Subscription Started'), ('NEW_PRODUCT', 'New Product Added'), ('NEW_ORDER', 'New Order'), ('SYSTEM', 'System Message')], max_length=20)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
